modLoader = "javafml" #mandatory
loaderVersion = "[42,)"
license = "MIT"
[[mods]] #mandatory
modId = "xpfactory" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Xp Factory" #mandatory
authors = "lamshiu" #optional
description = '''
This is a lightwieght forge minecraft mod developed by lamshiu. It provides an alternative to farm experience.
'''
[[dependencies.xpfactory]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[42,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.xpfactory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,1.20)"
ordering = "NONE"
side = "BOTH"
